/**
 * Redux Action types
 */
 export let ActionTypes

 ;(function(ActionTypes) {
   ActionTypes["TOGGLE_DEV_TOOLS_SUCCESS"] = "TOGGLE_DEV_TOOLS_SUCCESS"
   ActionTypes["OPEN_LOCAL_FOLDER_SUCCESS"] = "OPEN_LOCAL_FOLDER_SUCCESS"
   ActionTypes["REFRESH_APP_SUCCESS"] = "REFRESH_APP_SUCCESS"
   ActionTypes["SAVE_APP_SETTINGS_SUCCESS"] = "SAVE_APP_SETTINGS_SUCCESS"
   ActionTypes["ENSURE_SECURITY_TOKEN_SUCCESS"] = "ENSURE_SECURITY_TOKEN_SUCCESS"
   ActionTypes["LOAD_PROJECT_SUCCESS"] = "LOAD_PROJECT_SUCCESS"
   ActionTypes["SAVE_PROJECT_SUCCESS"] = "SAVE_PROJECT_SUCCESS"
   ActionTypes["DELETE_PROJECT_SUCCESS"] = "DELETE_PROJECT_SUCCESS"
   ActionTypes["CLOSE_PROJECT_SUCCESS"] = "CLOSE_PROJECT_SUCCESS"
   ActionTypes["LOAD_PROJECT_ASSETS_SUCCESS"] = "LOAD_PROJECT_ASSETS_SUCCESS"
   ActionTypes["EXPORT_PROJECT_SUCCESS"] = "EXPORT_PROJECT_SUCCESS"
   ActionTypes["UPDATE_PROJECT_TAG_SUCCESS"] = "UPDATE_PROJECT_TAG_SUCCESS"
   ActionTypes["DELETE_PROJECT_TAG_SUCCESS"] = "DELETE_PROJECT_TAG_SUCCESS"
   ActionTypes["LOAD_CONNECTION_SUCCESS"] = "LOAD_CONNECTION_SUCCESS"
   ActionTypes["SAVE_CONNECTION_SUCCESS"] = "SAVE_CONNECTION_SUCCESS"
   ActionTypes["DELETE_CONNECTION_SUCCESS"] = "DELETE_CONNECTION_SUCCESS"
   ActionTypes["SAVE_ASSET_METADATA_SUCCESS"] = "SAVE_ASSET_METADATA_SUCCESS"
   ActionTypes["LOAD_ASSET_METADATA_SUCCESS"] = "LOAD_ASSET_METADATA_SUCCESS"
   ActionTypes["ANY_OTHER_ACTION"] = "ANY_OTHER_ACTION_SUCCESS"
   ActionTypes["SHOW_ERROR"] = "SHOW_ERROR"
   ActionTypes["CLEAR_ERROR"] = "CLEAR_ERROR"
 })(ActionTypes || (ActionTypes = {}))
 